### PR TITLE
DetourBackend: Ensure PHDR is mapped at a page-aligned address.

### PR DESCRIPTION
**Pull request by ltfish**
Also fixes multiple issues:
- PHDR.p_offset should be the file offset, not the virtual memory
  address.
- Make sure PHDR.p_offset == PHDR.p_vaddr because of a weird issue that
  is (seemingly) inside glibc's dynamic loader.

### CODE REVIEW

**Comment by DennyDai** [comment]
#### Ensure PHDR is mapped at a page-aligned address.
On [detourbackend.py:421](https://github.com/angr/patcherex/blob/master/patcherex/backends/detourbackend.py#L421), segments are already rounded to multiple of 0x1000, therefore on [detourbackend.py:459](https://github.com/angr/patcherex/blob/master/patcherex/backends/detourbackend.py#L421), the value of phdr_start should also be page-aligned. 
Besides, on [detourbackend.py:465](https://github.com/angr/patcherex/blob/master/patcherex/backends/detourbackend.py#L465), ljust() append \x00 to the end of the binary to make the binary has length of phdr_start, which is page-aligned, so I think we might not need extra work here.

_(The code between lines 421-459 uses variable names that are difficult to understand, such as `blah, things, etc.`, so I renamed them to some more meaningful names and added some comments on the code in another branch, you can check it here [feat/multiarch : detourbackends/_elf.py](https://github.com/angr/patcherex/blob/feat/multiarch/patcherex/backends/detourbackends/_elf.py#L97)_

#### Make sure PHDR.p_offset == PHDR.p_vaddr because of a weird issue that is (seemingly) inside glibc's dynamic loader.
May I know more detail about that dynamic loader issue? I had issue with glibc's dynamic loader before, and I solved it in feat/multiarch branch. I'm not sure if that was the same issue.
The problem I had was,
when I run `./program`, it cause segFault,
but when I run `/usr/ld-linux-so.2 ./program`, it runs properly.

**Comment by ltfish** [comment]
@DennyDai After a second thought, I think that I don't need to re-align `phdr_start` again. However, I still need to make sure the `p_offset` and `p_vaddr` of PHDR are the same.

```
The problem I had was,
when I run ./program, it cause segFault,
but when I run /usr/ld-linux-so.2 ./program, it runs properly.
```

This is the exact problem that I came across yesterday. It seems that `ld` uses `p_vaddr` while the glibc loader is using `p_offset` to find PHDR. I suppose glibc loader is incorrect, but it has been doing this for a long time, and maybe it is too late to change at this moment? The easy workaround is just to make sure `p_vaddr == p_offset` for PHDR.

**Comment by ltfish** [comment]
@DennyDai 

Here is the real issue:

```
                        potential_base = ((max(prev_seg[1], len(self.ncontent)) + 0xF) & ~0xF)
```

That is why in some cases `phdr_start` may not be page-aligned. Changing it to `0xfff` works.

**Comment by DennyDai** [comment]
It seems between [line 462](https://github.com/angr/patcherex/blob/fix/align_phdr_page/patcherex/backends/detourbackend.py#L462) and line 463, the assignment of self.phdr_start is missing (self.phdr_start will be referenced before assignment on line 465)
```python
self.phdr_start = blah[-1][1]
```
I guess that line of code was removed by mistake? :P

---

Besides, given that masking has been fixed, I think we can safely assume self.phdr_start is page-aligned, and then we can simplify the code a bit.

**Pull request merged**
